name: Build and Release WinForms Installer

on:  
  workflow_dispatch:
  push:
    branches: deployment  
  pull_request:
    branches: deployment

permissions:
  id-token: write
  contents: read

jobs:
  build_ubuntu_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Project Name from JSON
        run: |
          PROJECT_NAME=$(jq -r '.project_name' .github/workflows/data.json)
          echo "PROJECT_NAME=$PROJECT_NAME"
          echo $PROJECT_NAME > project_name.txt

      - name: Upload Project Name Artifact
        uses: actions/upload-artifact@v3
        with:
          name: project_name
          path: project_name.txt

  build:
    runs-on: windows-latest
    permissions: write-all    
    steps:
      - name: Download Project Name Artifact
        uses: actions/download-artifact@v3
        with:
          name: project_name

      - name: Set Environment Variable from Artifact
        shell: pwsh
        run: |
          $PROJECT_NAME = Get-Content project_name.txt
          Write-Host "Setting PROJECT_NAME as $PROJECT_NAME"
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV

      - name: Debug Environment Variables
        shell: pwsh
        run: |
          echo "PROJECT_NAME: ${{ env.PROJECT_NAME }}"

      - name: Load Project Configuration
        shell: pwsh
        run: |
          Write-Host "Using PROJECT_NAME=$env:PROJECT_NAME"

      # Example steps to use PROJECT_NAME
      # Add your build or deployment logic here
      - name: Dummy Step to Use Project Name
        shell: pwsh
        run: |
          Write-Host "Simulating build process for project $env:PROJECT_NAME"
