name: Test Envs

on:  
  workflow_dispatch:
  push:
    branches: deployment  
  pull_request:
    branches: deployment

jobs:
  Test-Envs:
    runs-on: ubuntu-latest
    steps:
      - name: add a new env variable  
        run: |
          echo "NAME=test" >> $env:GITHUB_ENV

      - name: modify env variable
        run: |
          echo "${{env.NAME}}"
